### ISSUE TITLE
unable to download pam's harvestcraft

### ISSUE THREAD

**Issue by tril0byte** [Nincraft/ModPackDownloader#104]
I'm not a java coder but this is the only mod in the pack that failed, I pasted only the error.
I suspect maybe something to do with the apostrophe in the filename.

`
01-10-2021 20:19:02.928 [pool-2-thread-132] ERROR com.nincraft.modpackdownloader.util.DownloadHelper - Could not download Pam's HarvestCraft 1.12.2zg.jar.
java.io.IOException: Server returned HTTP response code: 400 for URL: https://edge.forgecdn.net/files/2904/825/Pam's HarvestCraft 1.12.2zg.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at java.net.URL.openStream(URL.java:1140) ~[?:?]
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1025) ~[ModpackDownloader-cli-0.6.1.jar:?]
        at com.nincraft.modpackdownloader.util.DownloadHelper.downloadFile(DownloadHelper.java:63) ~[ModpackDownloader-cli-0.6.1.jar:?]
        at com.nincraft.modpackdownloader.util.DownloadHelper.downloadFile(DownloadHelper.java:36) ~[ModpackDownloader-cli-0.6.1.jar:?]
        at com.nincraft.modpackdownloader.handler.CurseFileHandler.downloadCurseMod(CurseFileHandler.java:48) ~[ModpackDownloader-cli-0.6.1.jar:?]
        at com.nincraft.modpackdownloader.handler.CurseFileHandler.downloadMod(CurseFileHandler.java:264) ~[ModpackDownloader-cli-0.6.1.jar:?]
        at com.nincraft.modpackdownloader.processor.DownloadModsProcessor.lambda$downloadMods$1(DownloadModsProcessor.java:49) ~[ModpackDownloader-cli-0.6.1.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

manifest.json:

`
{
  "minecraft": {
    "version": "1.12.2",
    "modLoaders": [
      {
        "id": "forge-14.23.5.2854",
        "primary": true
      }
    ]
  },
  "manifestType": "minecraftModpack",
  "manifestVersion": 1,
  "name": "Wii Gaming Resort Modpack",
  "version": "1.8.0",
  "author": "CitrusHappy",
  "files": [
    {
      "projectID": 240630,
      "fileID": 2728585,
      "required": true
    },
    {
      "projectID": 310812,
      "fileID": 2783832,
      "required": true
    },
    {
      "projectID": 238403,
      "fileID": 2443194,
      "required": true
    },
    {
      "projectID": 253449,
      "fileID": 2568751,
      "required": true
    },
    {
      "projectID": 284641,
      "fileID": 2516593,
      "required": true
    },
    {
      "projectID": 261251,
      "fileID": 2638317,
      "required": true
    },
    {
      "projectID": 228948,
      "fileID": 2891787,
      "required": true
    },
    {
      "projectID": 267939,
      "fileID": 2849443,
      "required": true
    },
    {
      "projectID": 237307,
      "fileID": 2937869,
      "required": true
    },
    {
      "projectID": 301364,
      "fileID": 2609434,
      "required": true
    },
    {
      "projectID": 248453,
      "fileID": 2785465,
      "required": true
    },
    {
      "projectID": 244559,
      "fileID": 2830252,
      "required": true
    },
    {
      "projectID": 222838,
      "fileID": 2645020,
      "required": true
    },
    {
      "projectID": 74120,
      "fileID": 2711439,
      "required": true
    },
    {
      "projectID": 271298,
      "fileID": 2709823,
      "required": true
    },
    {
      "projectID": 254602,
      "fileID": 2891841,
      "required": true
    },
    {
      "projectID": 247921,
      "fileID": 2670570,
      "required": true
    },
    {
      "projectID": 225643,
      "fileID": 2846950,
      "required": true
    },
    {
      "projectID": 227875,
      "fileID": 2771611,
      "required": true
    },
    {
      "projectID": 227877,
      "fileID": 2817288,
      "required": true
    },
    {
      "projectID": 224535,
      "fileID": 2443253,
      "required": true
    },
    {
      "projectID": 243478,
      "fileID": 2745657,
      "required": true
    },
    {
      "projectID": 229002,
      "fileID": 2735197,
      "required": true
    },
    {
      "projectID": 222880,
      "fileID": 2926428,
      "required": true
    },
    {
      "projectID": 270789,
      "fileID": 2920436,
      "required": true
    },
    {
      "projectID": 69162,
      "fileID": 2920433,
      "required": true
    },
    {
      "projectID": 59693,
      "fileID": 2824328,
      "required": true
    },
    {
      "projectID": 245174,
      "fileID": 2755787,
      "required": true
    },
    {
      "projectID": 69163,
      "fileID": 2926431,
      "required": true
    },
    {
      "projectID": 294202,
      "fileID": 2563073,
      "required": true
    },
    {
      "projectID": 264684,
      "fileID": 2606175,
      "required": true
    },
    {
      "projectID": 229045,
      "fileID": 2745548,
      "required": true
    },
    {
      "projectID": 245755,
      "fileID": 2859589,
      "required": true
    },
    {
      "projectID": 229046,
      "fileID": 2745549,
      "required": true
    },
    {
      "projectID": 229048,
      "fileID": 2745550,
      "required": true
    },
    {
      "projectID": 229049,
      "fileID": 2745551,
      "required": true
    },
    {
      "projectID": 229050,
      "fileID": 2745546,
      "required": true
    },
    {
      "projectID": 271384,
      "fileID": 2920434,
      "required": true
    },
    {
      "projectID": 220698,
      "fileID": 2832138,
      "required": true
    },
    {
      "projectID": 255232,
      "fileID": 2830265,
      "required": true
    },
    {
      "projectID": 283644,
      "fileID": 2694382,
      "required": true
    },
    {
      "projectID": 241319,
      "fileID": 2761319,
      "required": true
    },
    {
      "projectID": 272514,
      "fileID": 2920596,
      "required": true
    },
    {
      "projectID": 59751,
      "fileID": 2684780,
      "required": true
    },
    {
      "projectID": 228525,
      "fileID": 2836960,
      "required": true
    },
    {
      "projectID": 231868,
      "fileID": 2822401,
      "required": true
    },
    {
      "projectID": 238003,
      "fileID": 2559089,
      "required": true
    },
    {
      "projectID": 253043,
      "fileID": 2807433,
      "required": true
    },
    {
      "projectID": 293704,
      "fileID": 2809046,
      "required": true
    },
    {
      "projectID": 225194,
      "fileID": 2491032,
      "required": true
    },
    {
      "projectID": 356646,
      "fileID": 2852431,
      "required": true
    },
    {
      "projectID": 223525,
      "fileID": 2916129,
      "required": true
    },
    {
      "projectID": 224641,
      "fileID": 2861573,
      "required": true
    },
    {
      "projectID": 221857,
      "fileID": 2904825,
      "required": true
    },
    {
      "projectID": 250822,
      "fileID": 2464981,
      "required": true
    },
    {
      "projectID": 294269,
      "fileID": 2701616,
      "required": true
    },
    {
      "projectID": 226321,
      "fileID": 2537917,
      "required": true
    },
    {
      "projectID": 244147,
      "fileID": 2568537,
      "required": true
    },
    {
      "projectID": 297621,
      "fileID": 2771463,
      "required": true
    },
    {
      "projectID": 250277,
      "fileID": 2722271,
      "required": true
    },
    {
      "projectID": 227441,
      "fileID": 2456007,
      "required": true
    },
    {
      "projectID": 227443,
      "fileID": 2920505,
      "required": true
    },
    {
      "projectID": 298187,
      "fileID": 2928313,
      "required": true
    },
    {
      "projectID": 224663,
      "fileID": 2938332,
      "required": true
    },
    {
      "projectID": 238590,
      "fileID": 2715827,
      "required": true
    },
    {
      "projectID": 250290,
      "fileID": 2665849,
      "required": true
    },
    {
      "projectID": 314904,
      "fileID": 2819669,
      "required": true
    },
    {
      "projectID": 251407,
      "fileID": 2624712,
      "required": true
    },
    {
      "projectID": 255308,
      "fileID": 2698950,
      "required": true
    },
    {
      "projectID": 223008,
      "fileID": 2828357,
      "required": true
    },
    {
      "projectID": 251974,
      "fileID": 2884990,
      "required": true
    },
    {
      "projectID": 264231,
      "fileID": 2939529,
      "required": true
    },
    {
      "projectID": 228027,
      "fileID": 2574880,
      "required": true
    },
    {
      "projectID": 229708,
      "fileID": 2893083,
      "required": true
    },
    {
      "projectID": 313816,
      "fileID": 2851670,
      "required": true
    },
    {
      "projectID": 235279,
      "fileID": 2915375,
      "required": true
    },
    {
      "projectID": 268704,
      "fileID": 2661859,
      "required": true
    },
    {
      "projectID": 244201,
      "fileID": 2717691,
      "required": true
    },
    {
      "projectID": 277064,
      "fileID": 2912859,
      "required": true
    },
    {
      "projectID": 231951,
      "fileID": 2799143,
      "required": true
    },
    {
      "projectID": 78778,
      "fileID": 2524058,
      "required": true
    },
    {
      "projectID": 267602,
      "fileID": 2915363,
      "required": true
    },
    {
      "projectID": 239197,
      "fileID": 2928558,
      "required": true
    },
    {
      "projectID": 284876,
      "fileID": 2558528,
      "required": true
    },
    {
      "projectID": 253689,
      "fileID": 2927679,
      "required": true
    },
    {
      "projectID": 279311,
      "fileID": 2549462,
      "required": true
    },
    {
      "projectID": 285439,
      "fileID": 2938103,
      "required": true
    },
    {
      "projectID": 340583,
      "fileID": 2939688,
      "required": true
    },
    {
      "projectID": 226406,
      "fileID": 2857869,
      "required": true
    },
    {
      "projectID": 243121,
      "fileID": 2924091,
      "required": true
    },
    {
      "projectID": 266515,
      "fileID": 2745321,
      "required": true
    },
    {
      "projectID": 250363,
      "fileID": 2746011,
      "required": true
    },
    {
      "projectID": 287683,
      "fileID": 2942431,
      "required": true
    },
    {
      "projectID": 223628,
      "fileID": 2629023,
      "required": true
    },
    {
      "projectID": 254268,
      "fileID": 2829232,
      "required": true
    },
    {
      "projectID": 233105,
      "fileID": 2745846,
      "required": true
    },
    {
      "projectID": 229769,
      "fileID": 2861235,
      "required": true
    },
    {
      "projectID": 74924,
      "fileID": 2713386,
      "required": true
    },
    {
      "projectID": 285473,
      "fileID": 2569880,
      "required": true
    },
    {
      "projectID": 229218,
      "fileID": 2855967,
      "required": true
    },
    {
      "projectID": 244258,
      "fileID": 2880863,
      "required": true
    },
    {
      "projectID": 223094,
      "fileID": 2482481,
      "required": true
    },
    {
      "projectID": 220318,
      "fileID": 2715506,
      "required": true
    },
    {
      "projectID": 250398,
      "fileID": 2926366,
      "required": true
    },
    {
      "projectID": 226447,
      "fileID": 2477566,
      "required": true
    },
    {
      "projectID": 285492,
      "fileID": 2705304,
      "required": true
    },
    {
      "projectID": 353447,
      "fileID": 2928808,
      "required": true
    },
    {
      "projectID": 296633,
      "fileID": 2699034,
      "required": true
    },
    {
      "projectID": 70492,
      "fileID": 2516215,
      "required": true
    },
    {
      "projectID": 70496,
      "fileID": 2518031,
      "required": true
    },
    {
      "projectID": 224791,
      "fileID": 2822288,
      "required": true
    },
    {
      "projectID": 254317,
      "fileID": 2932048,
      "required": true
    },
    {
      "projectID": 240950,
      "fileID": 2707390,
      "required": true
    },
    {
      "projectID": 231484,
      "fileID": 2862651,
      "required": true
    },
    {
      "projectID": 228702,
      "fileID": 2745545,
      "required": true
    },
    {
      "projectID": 239286,
      "fileID": 2934381,
      "required": true
    },
    {
      "projectID": 264353,
      "fileID": 2508268,
      "required": true
    },
    {
      "projectID": 280510,
      "fileID": 2643711,
      "required": true
    },
    {
      "projectID": 254334,
      "fileID": 2871957,
      "required": true
    },
    {
      "projectID": 307806,
      "fileID": 2820815,
      "required": true
    },
    {
      "projectID": 242638,
      "fileID": 2746892,
      "required": true
    },
    {
      "projectID": 223150,
      "fileID": 2689602,
      "required": true
    },
    {
      "projectID": 227049,
      "fileID": 2564573,
      "required": true
    },
    {
      "projectID": 288885,
      "fileID": 2838777,
      "required": true
    },
    {
      "projectID": 292785,
      "fileID": 2915154,
      "required": true
    },
    {
      "projectID": 225946,
      "fileID": 2680883,
      "required": true
    },
    {
      "projectID": 248787,
      "fileID": 2496585,
      "required": true
    },
    {
      "projectID": 291126,
      "fileID": 2625854,
      "required": true
    },
    {
      "projectID": 236541,
      "fileID": 2878931,
      "required": true
    },
    {
      "projectID": 236542,
      "fileID": 2913484,
      "required": true
    },
    {
      "projectID": 237102,
      "fileID": 2835289,
      "required": true
    },
    {
      "projectID": 278882,
      "fileID": 2716712,
      "required": true
    },
    {
      "projectID": 238222,
      "fileID": 2803400,
      "required": true
    },
    {
      "projectID": 227639,
      "fileID": 2818055,
      "required": true
    },
    {
      "projectID": 227083,
      "fileID": 2518667,
      "required": true
    },
    {
      "projectID": 228756,
      "fileID": 2747935,
      "required": true
    },
    {
      "projectID": 229876,
      "fileID": 2483393,
      "required": true
    },
    {
      "projectID": 336272,
      "fileID": 2926821,
      "required": true
    },
    {
      "projectID": 250498,
      "fileID": 2699705,
      "required": true
    },
    {
      "projectID": 303422,
      "fileID": 2942671,
      "required": true
    },
    {
      "projectID": 237701,
      "fileID": 2560638,
      "required": true
    },
    {
      "projectID": 306770,
      "fileID": 2731963,
      "required": true
    },
    {
      "projectID": 310673,
      "fileID": 2830525,
      "required": true
    },
    {
      "projectID": 285612,
      "fileID": 2943191,
      "required": true
    },
    {
      "projectID": 299540,
      "fileID": 2706111,
      "required": true
    },
    {
      "projectID": 233258,
      "fileID": 2643715,
      "required": true
    },
    {
      "projectID": 223794,
      "fileID": 2747063,
      "required": true
    },
    {
      "projectID": 253874,
      "fileID": 2917323,
      "required": true
    },
    {
      "projectID": 237167,
      "fileID": 2891572,
      "required": true
    },
    {
      "projectID": 228815,
      "fileID": 2699055,
      "required": true
    },
    {
      "projectID": 243298,
      "fileID": 2704186,
      "required": true
    },
    {
      "projectID": 228816,
      "fileID": 2699056,
      "required": true
    },
    {
      "projectID": 230497,
      "fileID": 2450900,
      "required": true
    },
    {
      "projectID": 304024,
      "fileID": 2830114,
      "required": true
    },
    {
      "projectID": 228832,
      "fileID": 2645992,
      "required": true
    },
    {
      "projectID": 237746,
      "fileID": 2596867,
      "required": true
    },
    {
      "projectID": 237749,
      "fileID": 2902920,
      "required": true
    },
    {
      "projectID": 236078,
      "fileID": 2557111,
      "required": true
    },
    {
      "projectID": 308495,
      "fileID": 2916458,
      "required": true
    },
    {
      "projectID": 291786,
      "fileID": 2701203,
      "required": true
    },
    {
      "projectID": 262823,
      "fileID": 2619249,
      "required": true
    },
    {
      "projectID": 257814,
      "fileID": 2941424,
      "required": true
    },
    {
      "projectID": 220495,
      "fileID": 2713186,
      "required": true
    },
    {
      "projectID": 271740,
      "fileID": 2707353,
      "required": true
    },
    {
      "projectID": 257818,
      "fileID": 2941425,
      "required": true
    },
    {
      "projectID": 60089,
      "fileID": 2671937,
      "required": true
    },
    {
      "projectID": 223852,
      "fileID": 2887858,
      "required": true
    },
    {
      "projectID": 238891,
      "fileID": 2922489,
      "required": true
    },
    {
      "projectID": 256717,
      "fileID": 2666198,
      "required": true
    },
    {
      "projectID": 231095,
      "fileID": 2720655,
      "required": true
    },
    {
      "projectID": 248370,
      "fileID": 2490058,
      "required": true
    },
    {
      "projectID": 51195,
      "fileID": 2687757,
      "required": true
    },
    {
      "projectID": 243363,
      "fileID": 2922065,
      "required": true
    },
    {
      "projectID": 281246,
      "fileID": 2821837,
      "required": true
    },
    {
      "projectID": 296289,
      "fileID": 2919737,
      "required": true
    },
    {
      "projectID": 261199,
      "fileID": 2814991,
      "required": true
    },
    {
      "projectID": 242818,
      "fileID": 2779848,
      "required": true
    },
    {
      "projectID": 64578,
      "fileID": 2858816,
      "required": true
    },
    {
      "projectID": 32274,
      "fileID": 2916002,
      "required": true
    },
    {
      "projectID": 251733,
      "fileID": 2641061,
      "required": true
    },
    {
      "projectID": 252848,
      "fileID": 2893527,
      "required": true
    },
    {
      "projectID": 225561,
      "fileID": 2678374,
      "required": true
    },
    {
      "projectID": 258426,
      "fileID": 2755790,
      "required": true
    },
    {
      "projectID": 241721,
      "fileID": 2920254,
      "required": true
    },
    {
      "projectID": 74072,
      "fileID": 2902483,
      "required": true
    },
    {
      "projectID": 278494,
      "fileID": 2845668,
      "required": true
    },
    {
      "projectID": 223908,
      "fileID": 2919673,
      "required": true
    },
    {
      "projectID": 277938,
      "fileID": 2904594,
      "required": true
    },
    {
      "projectID": 318602,
      "fileID": 2920604,
      "required": true
    },
    {
      "projectID": 255105,
      "fileID": 2643989,
      "required": true
    }
  ],
  "overrides": "overrides"
}
`

**Comment by AlexRMU** [comment]
\+
