### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by juraj-hrivnak** [Nincraft/ModPackDownloader#105]
This error shows up when I run the program. I have tested it on two computers, both with Windows.
The version of ModPackDownloader is: **0.6.1**

```java
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/nincraft/
modpackdownloader/cli/ModpackDownloaderCLI has been compiled by a more recent ve
rsion of the Java Runtime (class file version 55.0), this version of the Java Ru
ntime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by Nincodedo** [comment]
Upgrade to Java 11 or higher.
