### ISSUE TITLE
Couldn't download mod

### ISSUE THREAD

**Issue by Dark2932** [Nincraft/ModPackDownloader#121]
Version: ModpackDownloader CLI 0.7.2

[Scripts](https://github.com/Aurorisla/ModpackTemplate/blob/ec9189bd4cab6b86f924ea8fb7a291dcb01c7d4e/.github/workflows/download.yml) | [manifest.json](https://github.com/Aurorisla/ModpackTemplate/blob/ec9189bd4cab6b86f924ea8fb7a291dcb01c7d4e/modpack/manifest.json)
Logs:
```
Run cd ./
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
07:38:40.470 [main] INFO  com.nincraft.modpackdownloader.cli.ModpackDownloaderCLI:15 - Starting ModpackDownloaderManager with arguments: [-manifest, modpack/manifest.json, -folder, modpack/mods]
07:38:41.035 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.036 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.036 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.037 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.037 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.039 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.040 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.042 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.043 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.044 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.044 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.045 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.046 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.048 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.050 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.051 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.051 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.052 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.052 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.053 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.055 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.056 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.057 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.059 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.059 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.060 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.062 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.063 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.063 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.064 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.065 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.066 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.066 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.068 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.068 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.070 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.070 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.073 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.076 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.076 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.077 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.077 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.077 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.078 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.078 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.079 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.079 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.093 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.094 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.095 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.096 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.097 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.098 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.098 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.099 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.100 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.101 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.102 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.102 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.103 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.104 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.105 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.105 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.106 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.107 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.108 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
07:38:41.108 [main] ERROR com.nincraft.modpackdownloader.container.CurseFile:90 - java.net.UnknownHostException: addons-ecs.forgesvc.net
Exception in thread "main" java.lang.NullPointerException
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.lambda$new$0(AbstractProcessor.java:33)
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.buildModList(AbstractProcessor.java:113)
	at com.nincraft.modpackdownloader.processor.DownloadModsProcessor.init(DownloadModsProcessor.java:62)
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.process(AbstractProcessor.java:70)
	at com.nincraft.modpackdownloader.ModpackDownloaderManager.downloadMods(ModpackDownloaderManager.java:71)
	at com.nincraft.modpackdownloader.ModpackDownloaderManager.processManifests(ModpackDownloaderManager.java:53)
	at com.nincraft.modpackdownloader.cli.ModpackDownloaderCLI.main(ModpackDownloaderCLI.java:35)
Error: Process completed with exit code 1.
```

**Comment by paczek654321** [comment]
same
