### ISSUE TITLE
CLI crashes with NullPointerException (0.5.3)

### ISSUE THREAD

**Issue by mount2010** [Nincraft/ModPackDownloader#97]
The CLI of MPD 0.5.3 crashes entirely on an Ubuntu 18.04.3 LTS x86_64 server. I have tried both Java 8 and Java 11. The crash log is below:

```
22:06:24.038 [main] INFO  com.nincraft.modpackdownloader.cli.ModpackDownloaderCLI:15 - Starting ModpackDownloaderManager with arguments: []
Exception in thread "main" java.lang.NullPointerException
	at com.nincraft.modpackdownloader.container.CurseFile.init(CurseFile.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.buildModList(AbstractProcessor.java:112)
	at com.nincraft.modpackdownloader.processor.DownloadModsProcessor.init(DownloadModsProcessor.java:58)
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.process(AbstractProcessor.java:70)
	at com.nincraft.modpackdownloader.ModpackDownloaderManager.downloadMods(ModpackDownloaderManager.java:80)
	at com.nincraft.modpackdownloader.ModpackDownloaderManager.processManifests(ModpackDownloaderManager.java:55)
	at com.nincraft.modpackdownloader.cli.ModpackDownloaderCLI.main(ModpackDownloaderCLI.java:35)
```

This error exists for all arguments except -help.

**Comment by Nincodedo** [comment]
Could you provide the manifest.json you're using?

**Comment by mount2010** [comment]
[Mountpack.zip](https://github.com/Nincraft/ModPackDownloader/files/3987684/Mountpack.zip)

This was generated with GDLauncher 0.12.3. I'm not sure if GDLauncher manifests exactly match Twitch Launcher's (through, I would prefer it!).

```
java -jar ModpackDownloader-cli-0.5.3+SNAPSHOT.jar -manifest manifest.json -folder mods
09:43:59.400 [main] INFO  com.nincraft.modpackdownloader.cli.ModpackDownloaderCLI:15 - Starting ModpackDownloaderManager with arguments: [-manifest, manifest.json, -folder, mods]
Exception in thread "main" java.lang.NullPointerException
	at com.nincraft.modpackdownloader.container.CurseFile.init(CurseFile.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.buildModList(AbstractProcessor.java:112)
	at com.nincraft.modpackdownloader.processor.DownloadModsProcessor.init(DownloadModsProcessor.java:58)
	at com.nincraft.modpackdownloader.processor.AbstractProcessor.process(AbstractProcessor.java:70)
	at com.nincraft.modpackdownloader.ModpackDownloaderManager.downloadMods(ModpackDownloaderManager.java:80)
	at com.nincraft.modpackdownloader.ModpackDownloaderManager.processManifests(ModpackDownloaderManager.java:55)
	at com.nincraft.modpackdownloader.cli.ModpackDownloaderCLI.main(ModpackDownloaderCLI.java:35)
```

**Comment by Nincodedo** [comment]
Thank you. Looks like Cloudflare is blocking our downloader. This will take some time to fix.

**Comment by Nincodedo** [comment]
This has finally been fixed.
